services:
  scraper:
    build: ./scraper
    image: ghcr.io/mkapusnik/ha-bvk/scraper:la
    environment:
      - BVK_USERNAME=${BVK_USERNAME}
      - BVK_PASSWORD=${BVK_PASSWORD}
      - CHECK_INTERVAL_HOURS=${CHECK_INTERVAL_HOURS:-1}
      - TZ=Europe/Prague
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  api:
    build: ./api
    image: ghcr.io/mkapusnik/ha-bvk/api:latest
    volumes:
      - ./data:/app/data
    ports:
      - "8100:8000"
    restart: unless-stopped
